name: "CICD for Nginx using Dockerfile"
on:
  push:
    branches: ["main"]
    #path-ignore:
    #  - "src/**"
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  nginx-image-build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER__ACCESS__TOKEN }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/saikumar27295/devops:saikumar
